### ISSUE TITLE
Support Android 11, SDK 30

### ISSUE THREAD

**Issue by zhombie** [fondesa/kpermissions#181]
### Description
Hello, first of all, thanks for library. I am reading code base till now & I am not ready to contribute this feature request on my own yet. What about supporting Android 11? Some "important" methods were deprecated & the new recommended ways were changed (for example, requestPermissions, google recommends to use registerForActivityResult)

**Comment by fondesa** [comment]
Hello, as you can see in https://github.com/fondesa/kpermissions/blob/master/android-config.properties, this library already supports Android 11.

All the deprecations related to Android 11 are already fixed in a previous PR.

The API you are talking about is not related to Android 11, but to the dependency `androidx.fragment`.
Unfortunately, the release of  `androidx.fragment` which contains the new API is still in `rc`.

I'll update that dependency only when it will become stable since I don't want to depend on not-stable dependencies.

**Comment by zhombie** [comment]
Sorry, I have tried to update dependencies with sdk, so I faced issues, also extension function permissionRequest.send {} did not return the result. That's why I returned to the last stable versions as library
