### ISSUE TITLE
Manifest.permission.POST_NOTIFICATIONS Not working 

### ISSUE THREAD

**Issue by nikedlab** [fondesa/kpermissions#304]
New permission https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS not handled.
Wrong message is shown about allowing access to device storage and that's the end

**Comment by fondesa** [comment]
Are you running this on an Android device with API < 33?
If so, this issue is not related to this library but to how Android works.
Since this permission does not exist on devices with API < 33, it's handled as a permanently denied permission by the Android OS.
My recommendation is simply creating the `POST_NOTIFICATIONS` request only on API >= 33.
Feel free to re-open this issue if I wasn't clear enough or I misunderstood something.
